---
- hosts: all
  become: yes
  #vars_files: vault/sikret.yml

  tasks:
    - import_tasks: tasks/dyski.yml
      tags:
          - never
          - dyski


  roles:
    - role: system
      tags:   ### chyba z tego taga trza zrezygnować....
          - system ###??? tagować to tutaj, czy lepiej w roles/system/tasks już pojedynczo?????????????????????? albo i niee kurwa!!!!

