---
- hosts: all
  become: yes

  tasks:
    - import_tasks: tasks/dyski.yml
      tags:
          - never
          - dyski


  roles:
    - role: system
      tags:
          - system ###??? tagować to tutaj, czy lepiej w roles już pojedynczo??????????????????????

