username: tg

sshd_port_1: 22
sshd_port_2: 2803

packages:
  - vim
  - htop
  - neofetch
  - tmux 
  - speedtest-cli
  - iperf
  - iperf3
  - net-tools
  - whois
  - lvm2

lab_raid_level: 1
lab_mdadm_device: '/dev/md127'
lab_block_devices:
    - '/dev/sdb'
    - '/dev/sdc'

lab_pv_name: '/dev/md127'
lab_vg_name: 'vgdata'
lab_lv_name: 'lvdata'
lab_lv_size: '100%FREE'
lab_fs_type: 'ext4'
lab_label: 'gpt'
lab_mntpoint_path: '/mnt/DATA'
lab_mntpoint_mode: '755'

